name: My First WorkFlow
on:
  push:
    branches:
    - "deploy"
jobs:
  echo_the_date:
    runs-on: ubuntu-latest
    steps:
    - name: echo the date
      run: echo "The current date and time is $(date)"
    - name: echo the current branch
      run: echo ${{github.ref_name}}

  test_and_deploy:
    runs-on: ubuntu-latest
    env: 
      OPENWEATHER_API: ${{secrets.openweathermap_api}}
    steps:
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup maven
      uses: stCarolas/setup-maven@v4.3
      with: 
        maven-version: 3.8.2  
    - name: Checkout the source
      uses: action/checkout@v3

    - name: run test
      run: mvn clean test